CREATE TABLE LISTS (
    list_id SERIAL PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TASKS (
    task_id SERIAL PRIMARY KEY,
    list_id INT NOT NULL,
    text VARCHAR(100) NOT NULL,
    position_order INT NOT NULL,
    is_done BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_list FOREIGN KEY (list_id) REFERENCES LISTS(list_id) ON DELETE CASCADE
);