CREATE TABLE USERS (
    user_id SERIAL PRIMARY KEY,
    email VARCHAR(20) NOT NULL UNIQUE,
    username VARCHAR(20) NOT NULL UNIQUE,
    password_hash VARCHAR(200) NOT NULL,
    date_registered TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE LISTS (
    list_id SERIAL PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR(50) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
);

CREATE TABLE TASKS (
    task_id SERIAL PRIMARY KEY,
    list_id INT NOT NULL,
    text VARCHAR(100) NOT NULL,
    position_order INT NOT NULL,
    is_done BOOLEAN DEFAULT FALSE,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_list FOREIGN KEY (list_id) REFERENCES LISTS(list_id) ON DELETE CASCADE
);